var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/9d648_next_b19d149d._.js")
R.c("server/chunks/9d648_next-auth_fae9689a._.js")
R.c("server/chunks/9d648_openid-client_37641fc7._.js")
R.c("server/chunks/9d648_jose_dist_node_cjs_e1419f31._.js")
R.c("server/chunks/9d648_d58cfa44._.js")
R.c("server/chunks/[root-of-the-server]__ebbd07a4._.js")
R.m("[project]/cafe-management-system/.next-internal/server/app/api/auth/[...nextauth]/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/cafe-management-system/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/cafe-management-system/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/cafe-management-system/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/cafe-management-system/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
